version: "3.8"

services:
  db_postgres:
    container_name: postgres_youtube_clon
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: youtube_clon
    volumes:
      - ./pgdata:/varlib/postgresql/data
    ports:
      - "5432:5432"

  clon_youtube:
    container_name: clon_youtube
    volumes:
      - .:/clon_youtube
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
    depends_on:
      - db_postgres
